/**
 * Mock / Demo AI Provider
 * ------------------------------------------------------------
 * Used when AI_PROVIDER=mock or when no API key is configured.
 * Lets the entire app (chat, RAG, FIR, voice, OCR, translation)
 * run end-to-end without any external service or cost.
 *
 * All output is clearly and honestly labeled as demo content —
 * this file must never be used to fabricate real legal answers.
 */

import type {
  AIProvider,
  ChatMessage,
  EmbeddingResult,
  LLMCompletionOptions,
  LLMStreamChunk,
  OCRResult,
  TranscriptionResult,
  TranslationResult,
} from "./provider";

const DEMO_DISCLAIMER =
  "[DEMO MODE] This response was generated by LegalSetu's mock AI provider for demonstration purposes only. It is not real legal information.";

function hashToVector(text: string, dims = 1536): number[] {
  // Deterministic pseudo-embedding so demo retrieval is stable
  // and repeatable across runs (NOT a real embedding model).
  const vec = new Array(dims).fill(0);
  for (let i = 0; i < text.length; i++) {
    const idx = (text.charCodeAt(i) * (i + 1)) % dims;
    vec[idx] += (text.charCodeAt(i) % 13) / 13;
  }
  const norm = Math.sqrt(vec.reduce((s, v) => s + v * v, 0)) || 1;
  return vec.map((v) => v / norm);
}

function lastUserMessage(messages: ChatMessage[]): string {
  return [...messages].reverse().find((m) => m.role === "user")?.content ?? "";
}

export class MockProvider implements AIProvider {
  name = "mock";
  isDemo = true;

  async complete(options: LLMCompletionOptions): Promise<string> {
    const query = lastUserMessage(options.messages);
    return this.buildDemoAnswer(query);
  }

  async *streamComplete(
    options: LLMCompletionOptions
  ): AsyncGenerator<LLMStreamChunk> {
    const full = await this.complete(options);
    const words = full.split(" ");
    for (const word of words) {
      await new Promise((r) => setTimeout(r, 12));
      yield { delta: word + " ", done: false };
    }
    yield { delta: "", done: true };
  }

  async embed(text: string): Promise<EmbeddingResult> {
    return { embedding: hashToVector(text), dimensions: 1536 };
  }

  async embedBatch(texts: string[]): Promise<EmbeddingResult[]> {
    return Promise.all(texts.map((t) => this.embed(t)));
  }

  async transcribe(
    _audio: Buffer,
    _mimeType: string
  ): Promise<TranscriptionResult> {
    return {
      text: "[DEMO MODE] This is a simulated transcription of your voice input.",
      language: "en",
      confidence: 0.5,
    };
  }

  async translate(
    text: string,
    targetLanguage: string,
    sourceLanguage = "auto"
  ): Promise<TranslationResult> {
    return {
      text: `[${targetLanguage.toUpperCase()} DEMO TRANSLATION] ${text}`,
      sourceLanguage,
      targetLanguage,
    };
  }

  async ocr(_image: Buffer, _mimeType: string): Promise<OCRResult> {
    return {
      text: "[DEMO MODE] Simulated OCR output. Configure OCR_PROVIDER to extract real text from images.",
      confidence: 0.5,
    };
  }

  private buildDemoAnswer(query: string): string {
    return `${DEMO_DISCLAIMER}

**Regarding your question:** "${query.slice(0, 200)}"

In demo mode, LegalSetu cannot provide a grounded legal answer because no real AI provider or verified legal corpus is connected. In production mode (with AI_PROVIDER=openai and an ingested legal source database), this response would be generated strictly from retrieved, verified legal documents with full citations.

**What this demo response demonstrates:**
- Streaming response rendering
- Citation card layout (see sample sources below)
- Evidence-level indicator behavior
- The mandatory disclaimer pattern

This is informational content only and is not a substitute for advice from a qualified lawyer.`;
  }
}
