/**
 * Mock / Demo AI Provider
 * ------------------------------------------------------------
 * Used when AI_PROVIDER=mock or when no API key is configured.
 * Lets the entire app (chat, RAG, FIR, voice, OCR, translation)
 * run end-to-end without any external service or cost.
 *
 * All output is clearly and honestly labeled as demo content —
 * this file must never be used to fabricate real legal answers.
 */

import type {
  AIProvider,
  ChatMessage,
  EmbeddingResult,
  LLMCompletionOptions,
  LLMStreamChunk,
  OCRResult,
  TranscriptionResult,
  TranslationResult,
} from "./provider";

const DEMO_DISCLAIMER =
  "[DEMO MODE] This response was generated by LegalSetu's mock AI provider for demonstration purposes only. It is not real legal information.";

function hashToVector(text: string, dims = 1536): number[] {
  // Deterministic pseudo-embedding so demo retrieval is stable
  // and repeatable across runs (NOT a real embedding model).
  const vec = new Array(dims).fill(0);
  for (let i = 0; i < text.length; i++) {
    const idx = (text.charCodeAt(i) * (i + 1)) % dims;
    vec[idx] += (text.charCodeAt(i) % 13) / 13;
  }
  const norm = Math.sqrt(vec.reduce((s, v) => s + v * v, 0)) || 1;
  return vec.map((v) => v / norm);
}

function lastUserMessage(messages: ChatMessage[]): string {
  return [...messages].reverse().find((m) => m.role === "user")?.content ?? "";
}

export class MockProvider implements AIProvider {
  name = "mock";
  isDemo = true;

  async complete(options: LLMCompletionOptions): Promise<string> {
    const query = lastUserMessage(options.messages);

    // Some callers (e.g. app/api/documents/[id]/analyze/route.ts) require
    // a strict JSON response and will JSON.parse() + zod-validate whatever
    // we return. The generic prose demo answer below is NOT valid JSON, so
    // those callers would fail on every single request in demo mode and
    // silently fall back to "Not detected" everywhere. Detect that case
    // from the prompt itself and answer with valid, clearly-labeled demo
    // JSON instead, so demo mode actually demonstrates the real output
    // shape instead of masking it behind a fallback.
    if (this.wantsJsonAnalysis(options.messages)) {
      return this.buildDemoAnalysisJson(query);
    }

    return this.buildDemoAnswer(query);
  }

  private wantsJsonAnalysis(messages: ChatMessage[]): boolean {
    const combined = messages.map((m) => m.content).join("\n");
    return (
      combined.includes("Return ONLY valid JSON") ||
      combined.includes('"documentType"')
    );
  }

  private buildDemoAnalysisJson(query: string): string {
    // Matches analysisResultSchema in lib/validation/schemas.ts exactly.
    // Every field is explicitly labeled as demo content per this file's
    // header comment — never real legal analysis.
    const analysis = {
      caseName: "[DEMO MODE] Sample v. Case Name",
      judge: "[DEMO MODE] Presiding officer would be extracted here.",
      date: "[DEMO MODE] Document date would be extracted here.",
      decisionSummary:
        "[DEMO MODE] This is a simulated analysis. Configure AI_PROVIDER=gemini (or openai) with a valid API key to get a real, grounded analysis of the uploaded document's actual content.",
      keyFindings: [
        "[DEMO MODE] Key findings would be extracted here from the real document text.",
      ],
      nextSteps: [
        "[DEMO MODE] Recommended next steps would be extracted here.",
        `[DEMO MODE] Original prompt excerpt: "${query.slice(0, 120)}"`,
      ],
    };
    return JSON.stringify(analysis);
  }

  async *streamComplete(
    options: LLMCompletionOptions
  ): AsyncGenerator<LLMStreamChunk> {
    const full = await this.complete(options);
    const words = full.split(" ");
    for (const word of words) {
      await new Promise((r) => setTimeout(r, 12));
      yield { delta: word + " ", done: false };
    }
    yield { delta: "", done: true };
  }

  async embed(text: string): Promise<EmbeddingResult> {
    return { embedding: hashToVector(text), dimensions: 1536 };
  }

  async embedBatch(texts: string[]): Promise<EmbeddingResult[]> {
    return Promise.all(texts.map((t) => this.embed(t)));
  }

  async transcribe(
    _audio: Buffer,
    _mimeType: string
  ): Promise<TranscriptionResult> {
    return {
      text: "[DEMO MODE] This is a simulated transcription of your voice input.",
      language: "en",
      confidence: 0.5,
    };
  }

  async translate(
    text: string,
    targetLanguage: string,
    sourceLanguage = "auto"
  ): Promise<TranslationResult> {
    return {
      text: `[${targetLanguage.toUpperCase()} DEMO TRANSLATION] ${text}`,
      sourceLanguage,
      targetLanguage,
    };
  }

  async ocr(_image: Buffer, _mimeType: string): Promise<OCRResult> {
    return {
      text: "[DEMO MODE] Simulated OCR output. Configure OCR_PROVIDER to extract real text from images.",
      confidence: 0.5,
    };
  }

  private buildDemoAnswer(query: string): string {
    return `${DEMO_DISCLAIMER}

**Regarding your question:** "${query.slice(0, 200)}"

In demo mode, LegalSetu cannot provide a grounded legal answer because no real AI provider or verified legal corpus is connected. In production mode (with AI_PROVIDER=openai and an ingested legal source database), this response would be generated strictly from retrieved, verified legal documents with full citations.

**What this demo response demonstrates:**
- Streaming response rendering
- Citation card layout (see sample sources below)
- Evidence-level indicator behavior
- The mandatory disclaimer pattern

This is informational content only and is not a substitute for advice from a qualified lawyer.`;
  }
}